// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCxoDCY1rU-F26pFy9akeic2jxQFRrNTA',
    appId: '1:562827703140:web:f0847e7b64683239060071',
    messagingSenderId: '562827703140',
    projectId: 'flutter-chat-app-36771',
    authDomain: 'flutter-chat-app-36771.firebaseapp.com',
    storageBucket: 'flutter-chat-app-36771.firebasestorage.app',
    measurementId: 'G-631LF2X8BK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-T9WpKHxBg6fsSd5bcP3Q4VwbQKt1WXM',
    appId: '1:562827703140:android:463a92e30025bd83060071',
    messagingSenderId: '562827703140',
    projectId: 'flutter-chat-app-36771',
    storageBucket: 'flutter-chat-app-36771.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcK-20AabPICeEhuVj2YSioRy7b3YqWuw',
    appId: '1:562827703140:ios:cde4b2ab990b4b09060071',
    messagingSenderId: '562827703140',
    projectId: 'flutter-chat-app-36771',
    storageBucket: 'flutter-chat-app-36771.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCcK-20AabPICeEhuVj2YSioRy7b3YqWuw',
    appId: '1:562827703140:ios:cde4b2ab990b4b09060071',
    messagingSenderId: '562827703140',
    projectId: 'flutter-chat-app-36771',
    storageBucket: 'flutter-chat-app-36771.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBCxoDCY1rU-F26pFy9akeic2jxQFRrNTA',
    appId: '1:562827703140:web:86b36a98304742b3060071',
    messagingSenderId: '562827703140',
    projectId: 'flutter-chat-app-36771',
    authDomain: 'flutter-chat-app-36771.firebaseapp.com',
    storageBucket: 'flutter-chat-app-36771.firebasestorage.app',
    measurementId: 'G-JX9SK9XT4G',
  );
}
